export const productPageSidebarLocator = {
  menuSidebarOpen: "#react-burger-menu-btn",
  allItems: "#inventory_sidebar_link",
  aboutLink: "#about_sidebar_link",
  logoutLink: "#logout_sidebar_link",
  resetLink: "#reset_sidebar_link",
  menuSidebarClose: "#react-burger-cross-menu",
  productNames: ".inventory_item_name",
  productDesc: ".inventory_item_desc",
  productPrices: ".inventory_item_price",
  addToCartBtns: ".btn.btn_primary.btn_small.btn_inventory",
  productCards: '[data-test="inventory-item"]',
  filterDropDown: ".product_sort_container",
  filterNamesAtoZ: "option[value='az']",
  filterNamesZtoA: "option[value='za']",
  filterPriceLowtoHigh: "option[value='lohi']",
  filterPriceHightoLow: "option[value='hilo']",
  cartLink: "[data-test='shopping-cart-link']",
};
